var MSG = {
  title: "PYLY (v00.01.09)",
  blocks: "Blocks",
  debug: "Debug",
  code: "Code",
  fail: "Fail",
  start: ":Start\r\n",
  reallyrun: "ReallRun?",
  stop: "\r\n:Stop",
  copyright:"Copyright © HERO CHILD TECH pyly.trtos.com",
  likeTooltip: "Save as a sample.",
  likeinputtitle:"New template name:",
  saveinputtitle:"Save File name:",
  runTooltip: "Program to run the workspace on the target board.",
  badCode: "Program error:\n%1",
  timeout: "Maximum execution iterations exceeded.",
  trashTooltip: "Discard all blocks.",
  catGpio:"Gpio",
  catDriver:"Driver",
  catSensor:"Sensor",
  catControl:"Control",
  catIot:"Iot",
  catPwm:"Pwm",
  catAnalog:"Analog input",
  catI2c:"I2c",
  catSpi:"Spi",
  catSerial:"Serial",
  catFile:"File",
  catSound:"Sound",
  catTcpip:"Tcp/IP",
  catTime:"Time",
  catLcd:"Lcd",
  catLcdBase:"Base",
  catLcdMiddle:"Middle",
  catLcdHigh:"High",
  catCamera:"Vision",
  catPrint:"Print",
  catLogic: "Logic",
  catLoops: "Loops",
  catMath: "Math",
  catText: "Text",
  catLists: "Lists",
  catColour: "Colour",
  catVariables: "Variables",
  catFunctions: "Functions",
  listVariable: "list",
  tempVariable: "temperature",
  textVariable: "text",
  deletethiscontext:"Delete %1 all %2 blocks?",
  httpRequestError: "There was a problem with the request.",
  linkAlert: "Share your blocks with this link:\n\n%1",
  hashError: "Sorry, '%1' doesn't correspond with any saved program.",
  xmlError: "Could not load your saved file. Perhaps it was created with a different version of Blockly?",
  badXml: "Error parsing XML:\n%1\n\nSelect 'OK' to abandon your changes or 'Cancel' to further edit the XML.",
  catGpio_write_title:"write io %1 to %2",
  catGpio_read_title:"read io %1",
  catGpio_mode_title:"set io %1 to %2",
  catGpio_value_high:"HIGH",
  catGpio_value_low:"LOW",
  catGpio_mode_out:"OUT",
  catGpio_mode_in:"IN",
  catGpio_led_title:"led %1 %2",
  catGPio_interrupt_title:"set interrupt %1  %2",
  catGPio_keydown_title:"if key %1 down%2 up %3",
  catPwm_period_ms_title:"set pwm %1 period %2 ms",
  catPwm_cycle_title:"write pwm %1 cycle %2 /1",
  catPwm_enable_title:"set pwm %1 %2 ",
  catPwm_value_enable:"ENABLE",
  catPwm_value_disenable:"DISENABLE",
  catSound_play_title:"play %1",
  catI2c_address_title:"create %1 address %2",
  catI2c_readreg_title:"read %1 reg %2",
  catI2c_writereg_title:"write %1 reg %2 value %3",
  catI2c_mpu6050_title:"gyroscope get %1",
  catSpi_readwrite_title:"read %1 write %2",
  catSerial_write_title:"send %1 context %2",
  catSerial_writeline_title:"send %1 line %2 ",
  catSerial_write_array_title:"send %1 array %2",
  catSerial_set_baudrate_title:"set %1 baudrate %2",
  catSerial_readstr_title:"read %1 string %2 byte",
  catSerial_dataavailable_title:"read %1 dataavailable timeout %2 ",
  catSerial_modbus_title:"write %1 baudrate %2 centext%3crc %4",
  catSerial_modbus_checknull:"null",
  catSerial_modbus_checkcrc16:"crc16",
  catSound_piano_title:"piano %1 beat %2",
  catSound_melody_title:"melody %1",
  catSound_effect_title:"effect %1",
  catSound_dance_title:"dance %1",
  catSound_playpath_title:"play path %1",
  catSound_record_title:"record duration %1 s",
  catSound_tts_title:"text to speech %1aip key%2 secret key%3",
  catAnalog_read_int_title:"read %1 analog",
  catAnalog_read_float_title:"read %1 voltage",
  catEthernet_ipaddress_title: "ipaddress %1 port %2",
  catEthernet_connect_title: "connect server %1",
  catEthernet_send_title: "send %1 context %2",
  catEthernet_revice_title: "revice %1 length %2",
  catPrint_to_title: "print %1 to %2",
  catPrint_console_title: "Console",
  catPrint_lcd_title: "Lcd",
  catPrint_net_title: "Net %1",
  catPrint_file_title: "File",
  catIot_send_title:"send %1 to %2 id %3",
  catIot_get_title:"get net variable %1",
  catIot_set_title:"set net variable %1 to %2",
  catIot_httpget_title:"http get from url %1",
  catIot_httppost_title:"http post data %1 to url %2",
  catLcd_writeline_title:"write %1 to lcd",
  catLcd_drawimage_title:"draw image %1 location (x%2y%3)",
  catLcd_showicons_title:"show icons %1 location (x%2y%3)",
  catLcd_showtrafficlight_title:"show trafficlight %1 location (x%2y%3)",
  catLcd_drawdot_title:"drawdot location (x%1y%2)color%3",
  catLcd_drawrect_title:"drawrect start (x1%1y1%2)end (x2%3y2%4)color%5",
  catLcd_drawline_title:"drawline start (x1%1y1%2)end (x2%3y2%4)color%5",
  catLcd_drawrectfill_title:"drawrectfill start (x1%1y1%2)end (x2%3y2%4)color%5",
  catLcd_drawtriangle_title:"drawtriangle Point A(x1%1y1%2)Point B(x2%3y2%4)Point C(x3%5y3%6) color%7",
  catLcd_filltriangle_title:"filltriangle Point A(x1%1y1%2)Point B(x2%3y2%4)Point C(x3%5y3%6) color%7",
  catLcd_drawcircle_title:"drawcircle location (x%1y%2)radius%3color%4",
  catLcd_drawcirclefill_title:"drawcirclefill location (x%1y%2)radius%3color%4",
  catLcd_drawclear_title:"draw clear %1",
  catLcd_writestring_title:"write string %1 font %2 location(x%3y%4) fontcolor%5 backcolor%6 alpacolor %7 ",
  catLcd_writestring1_title:"write string(vector)  %1 size %2 location(x%3y%4) fontcolor%5 backcolor%6 alpacolor %7 ",
  catLcd_drawawesome_title:"write awesome(vector)  %1 size %2 location(x%3y%4) fontcolor%5 backcolor%6 alpacolor %7 ",
  catLcd_screenshot_title:"screen shot",
  catLcd_screenshotdebug_title:"screen shot print",
  catLcd_screenprevie_title:"screen prievie",
  catTime_timeoption_year:"year",
  catTime_timeoption_month:"month",
  catTime_timeoption_day:"day",
  catTime_timeoption_hour:"hour",
  catTime_timeoption_minute:"minute",
  catTime_timeoption_second:"second",
  catTime_getnow_title:"now %1",
  catTime_sleep_title:"sleep %1 s",
  catTime_nowdate_title:"now date",
  catTime_nowtime_title:"now time",
  catTime_timer_title:"timer %1 timing(s)%2 execution %3",
  catTime_timerstart_title:"timer %1 start",
  catTime_thread_title:"thread%1 %2",
  catFile_write_title: "write %1 to %2",
  catFile_create_title: "write %1 create %2",
  catFile_writeline_title: "writeline %1 to %2",
  catFile_read_title: "read %1",
  catFile_readline_title: "read %1 line %2",
  catFile_readlines_title: "readlines %1",
  catFile_wget_title:"get resource %1",
  catI2c_mpu6050_gyro:"Gyro",
  catI2c_mpu6050_acc:"Acc",
  catI2c_mpu6050_temp:"Temp",
  catLcd_dotarray_title:"%1 %2 %3 %4 %5 %6 %7 %8 %9 %10 %11 %12 %13 %14 %15 %16 %17 %18 %19 %20 %21 %22 %23 %24 %25 %26 %27 %28 %29 %30 %31 %32 %33 %34 %35 %36 %37 %38 %39 %40 %41 %42 %43 %44 %45 %46 %47 %48 %49 %50 %51 %52 %53 %54 %55 %56 %57 %58 %59 %60 %61 %62 %63 %64 %65 %66 %67 %68 %69 %70 %71",
  catLcd_drawdotarray_title:"draw dotarray data%1 color%2 backcolor%3",
  catLcd_drawdotarraybit_title:"draw array bit(x %1 y%2) show %3",
  catLcd_selectarraydot_title:"select array dot(x %1 y%2) color %3",
  catLcd_getdotarraybit_title:"get array bit(x %1 y%2)",
  catLcd_drawdotarraymove_title:"draw array move(x %1 y%2)",
  catLcd_carinit_title:"%1init postion %2 %3 found %4 ",
  catLcd_carmove_title:"%1 %2 %3 step",
  catLcd_inittemp_title:"init temp(%1) location(x%2y%3)",
  catLcd_showtemp_title:"show temp(%1) (value)%2(max)%3",
  catLcd_map0init_title:"map0 init %1%2%3%4%5 %6%7%8%9%10 %11%12%13%14%15",
  catCamera_take_title:"take %1 photo",
  catCamera_previewconsole_title:"take %1 preview console",
  catCamera_showconsole_title:"take %1 show console",
  catCamera_takesize_title:"take %1 size  %2 picture",
  catCamera_baiduaip_title:"discern image%1 aip key%2 secret key%3",
  catCamera_baiduaip_helpurl:"http://pyly.trtos.com/",
  catCamera_baiduaip_tooltip:"use baidu ai discern image",
  catWeeemake_130motor_title:"weeemake 130motor port %1 speed %2",
  catWeeemake_dcmotor_title:"weeemake dcmotor port %1 speed %2",
  catWeeemake_humiture_title:"weeemake humiture port %1 index %2",
  catWeeemake_gassensor_title:"weeemake gassensor port %1",
  catWeeemake_flamesensor_title:"weeemake flamesensor port %1 index %2",
  catWeeemake_compasssensor_title:"weeemake compasssensor port %1 index %2",
  catWeeemake_ultrasondistancesensor_title:"weeemake ultrasonsensor distance port %1",
  catWeeemake_ultrasonshowrgbsensor_title:"weeemake ultrasonsensor showrgb port %1 index %2 color %3",
  catWeeemake_ultrasonshowrgbsensor_left:"left",
  catWeeemake_ultrasonshowrgbsensor_right:"right",
  catWeeemake_ultrasonshowrgbsensor_all:"all",
  catWeeemake_rgb5module_title:"weeemake rgb5module port %1 index %2 color %3",
  catWeeemake_rgbstrip_title:"weeemake rgbstttrip port %1 index %2 color %3",
  catWeeemake_joystick_title:"weeemake joystick port %1 index %2",
  catWeeemake_moisturesensor_title:"weeemake moisturesensor port %1",
  catWeeemake_pirsensor_title:"weeemake pirsensor port %1",
  catWeeemake_ds18b20_title:"weeemake ds18b20 port %1",
  catWeeemake_linefollower_title:"weeemake linefllower port %1 index %2",
  catWeeemake_colorsensor_setlight_title:"weeemake colorsensor port %1 setlight %2",
  catWeeemake_colorsensor_whitebalance_title:"weeemake colorsensor port %1 whitebalance",
  catWeeemake_colorsensor_getcolor_title:"weeemake colorsensor port %1 getcolor %2",
  catWeeemake_colorsensor_getcolor_light:"light component",
  catWeeemake_colorsensor_getcolor_red:"red component",
  catWeeemake_colorsensor_getcolor_green:"green component",
  catWeeemake_colorsensor_getcolor_blue:"blue component",
  catWeeemake_tiltswitch_title:"weeemake tiltswitch port %1 index %2",
  catWeeemake_4ledbutton_title:"weeemake 4ledbutton port %1 button %2 pressed ",
  catWeeemake_relay_title:"weeemake relay port %1 on %2",
  catWeeemake_atomizer_title:"weeemake atomizer port %1 on %2",
  catWeeemake_singleled_title:"weeemake singleled port %1 on %2",
  catWeeemake_uvsensor_title:"weeemake uvsensor port %1 type %2",
  catWeeemake_uvsensor_value:"digital component",
  catWeeemake_uvsensor_analog:"analog component",
  catWeeemake_pm2_5sensor_title:"weeemake pm2.5 sensor port %1 type %2",
  catWeeemake_barometersensor_title:"weeemake barometer sensor port %1",
  catWeeemake_watersensor_title:"weeemake water sensor port %1",
  catWeeemake_bot_title:"weeemake bot found %1 speed %2",
  catWeeemake_bot_forward:"forward",
  catWeeemake_bot_backward:"backward",
  catWeeemake_bot_trun_left:"turn left",
  catWeeemake_bot_trun_right:"trun right",
  catWeeemake_servo_title:"weeemake servo %1 angle %2",
  catWeeemake_potentiometer_title:"weeemake potentiometer %1",
  catWeeemake_openclose_open:"open",
  catWeeemake_openclose_close:"close",
  catWeeemake_humiture:"tempture",
  catWeeemake_temperature:"temperature",
  catText_eval_title:"evel%1",
  catText_replace_title:"%1replace%2to%3",
};